[workspace]
resolver = "2"
members = [
    "packet_proc",
    "packet",
    "server",
]

[profile.release]
lto = true
strip = true

[profile.dev.package.num-bigint-dig]
opt-level = 3

[profile.dev.package.rsa]
opt-level = 3
